# Generated by Django 5.0.6 on 2024-06-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Floreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=500)),
                ('unidad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
